apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    app: k8sproj
  ports:
    - name: http
      protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8sproj
  template:
    metadata:
      labels:
        app: k8sproj 
    spec:
      containers:
        - name: k8sproj
          image: thivagarrajad/pyimage:latest
          imagePullPolicy: Always